### ISSUE TITLE
Error: No transformer for 'application/x-' is installed.

### ISSUE THREAD

**Issue by BenRoe** [noxify/gridsome-source-git#32]
Hi,
i get the following error.
Is this because of a not supported file in the repo, or some code in the markdownfile?

```
▶ gridsome develop
Gridsome v0.7.23

Initializing plugins...
Error: No transformer for 'application/x-' is installed.
    at transformNodeContent (/Users/Ben/Git/gridsome-keycapsss-help/node_modules/gridsome/lib/store/transformNodeContent.js:12:13)
    at SyncBailWaterfallHook.eval [as call] (eval at create (/Users/Ben/Git/gridsome-keycapsss-help/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:16)
    at Collection.addNode (/Users/Ben/Git/gridsome-keycapsss-help/node_modules/gridsome/lib/store/Collection.js:72:50)
    at /Users/Ben/Git/gridsome-keycapsss-help/node_modules/@noxify/gridsome-source-git/index.js:76:42
    at async Promise.all (index 0)
    at async GitSource.createNodes (/Users/Ben/Git/gridsome-keycapsss-help/node_modules/@noxify/gridsome-source-git/index.js:74:9)
    at async /Users/Ben/Git/gridsome-keycapsss-help/node_modules/@noxify/gridsome-source-git/index.js:48:13
    at async Plugins.run (/Users/Ben/Git/gridsome-keycapsss-help/node_modules/gridsome/lib/app/Plugins.js:141:11)
```

gridsome.config.js
```
    {
      use: '@noxify/gridsome-source-git',
      options: {
        remote: 'https://github.com/BenRoe/Lily58L-Build-Guide.git',
        branch: 'master',
        target: 'content/public-github/lily58',
        typeName: 'GitPost'
      }
    },
```

**Comment by noxify** [comment]
Hi @BenRoe 

thanks for reporting.

I will check this.

Regards,
Marcus
